service: aws-billing-to-slack

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ce:GetCostAndUsage"
      Resource: "*"

functions:
  report_cost:
    handler: handler.report_cost

    events:
      # Every day at 11:00 UTC / 08am BRT
      - schedule: cron(0 11 * * ? *)

    environment:
      SLACK_WEBHOOK_URL: ${opt:slack_url}